name: rexios_dev
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.10.5
  firebase_analytics: ^9.0.2
  flutter_markdown: ^0.6.2
  url_launcher: ^6.0.7
  fast_ui: ^0.1.0
  get_it: ^7.2.0
  pub_api_client:
    git:
      url: https://github.com/Rexios80/pub_api_client
      ref: 3ca2b80a1fdc0f3f9859c02fa354e839f4fa4eb3
  github: ^9.0.0
  font_awesome_flutter: ^10.0.0-beta
  collection: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  rexios_lints: ^3.0.0
  flutter_native_splash: ^2.0.1+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/strings/

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: '#042a49'
  image: 'assets/images/icon.png'
  android: false
  ios: false