name: dart_cloud_run_template
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  jaguar: ^3.1.3
  jaguar_cors: ^3.0.2
  jaguar_dev_proxy: ^3.0.0

dev_dependencies:
  rexios_lints: ^3.0.0
  test: ^1.15.7
  test_process: ^2.0.0
  http: ^0.13.0
